name: Create Branch From Issue Version 0.1

on:
  issues:
    types: [opened]

jobs:
  create-branch-if-version0.1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read

    if: github.event.issue.milestone && github.event.issue.milestone.title == 'Version 0.1'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE="${{ github.event.issue.title }}"
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${SAFE_TITLE}"

          echo "Creating branch: $BRANCH_NAME"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout -b "$BRANCH_NAME" origin/main
          git push origin "$BRANCH_NAME"
